<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModSharp.Sharp.Extensions.CommandManager" Version="2.1.132" />
    <PackageReference Include="ModSharp.Sharp.Extensions.GameEventManager" Version="2.1.132" />
    <PackageReference Include="ModSharp.Sharp.Generator.Sdk" Version="2.1.132">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ModSharp.Sharp.Modules.ClientPreferences.Shared" Version="2.1.132" />
    <PackageReference Include="ModSharp.Sharp.Modules.MenuManager.Shared" Version="2.1.132" />
    <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.132" />
    <PackageReference Include="Sharp.Modules.AdminManager.Shared" Version="2.1.117" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZombieModSharp.Shared\ZombieModSharp.Shared.csproj" />
  </ItemGroup>
</Project>
